<?php

namespace AppBundle\Repository;

/**
 * ProgrammerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammerRepository extends \Doctrine\ORM\EntityRepository
{
}
