my:
    resource: "@MyBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
app_api:
    resource: '@AppBundle/Controller/Api'
    type: annotation
homepage:
    path: /
    defaults:
       _controller: AppBundle:Main:homepage

